project:
  type: website
  output-dir: docs

website:
  title: "Bangyao (Brian) Zhao"
  navbar: {}

format:
  html:
    page-layout: full
    theme: flatly
    css: styles.css
    toc: true

editor: visual

